sudo: false
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script: sbt clean coverage test
addons:
  apt:
    packages:
      - cwltool
after_success:
  - sbt coverageReport coveralls
  - src/bin/after_success.sh
deploy:
  provider: script
  script: src/bin/publish_release.sh
  on:
    tags: true