sudo: false
install: pip install cwltool
language: scala
scala:
  - 2.12.3
jdk:
  - oraclejdk8
script: sbt clean +coverage +test
after_success:
  - sbt coverageReport coverageAggregate coveralls
  - src/bin/after_success.sh
deploy:
  provider: script
  script: src/bin/publish_release.sh
  on:
    tags: true
