package wdl4s.wom.graph

class DeclarationNode extends GraphNode {
//  def name: String
//  def expression: Option[Expression]

  /**
    * Inputs that must be available before this graph node can be run.
    */
  override def inputPorts: Set[GraphNodePort.InputPort] = ???

  /**
    * Outputs that are generated by this GraphNode
    */
  override def outputPorts: Set[GraphNodePort.OutputPort] = ???
}
